# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d205d93d87b83c55876c4e8e09b315b269d89cfb04f5aa5dae7dd98edc7bdc5211cd6e7f3377753dd2fc704d7fa79a0885bafe663bd537c6f6082e62ac588c9f

test:
  secret_key_base: 6821a446e6358eb9cd97400a5f00648f9b0314f9a02b60b6f02ec202475989d84e2a0cfc4d6a796e51faffdf6880a16cb1d5b02052cf0139041e912aa12b5627

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
